name: release version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Git user
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "release-bot@example.com"

      - name: Create release branch
        run: |
          git checkout -b release-branch

      - name: Start SSH agent and add key
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run Maven release
        run: mvn release:prepare release:perform -B

      - name: Push release branch
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          GIT_SSH_COMMAND="ssh -i key.pem -o StrictHostKeyChecking=no" git push origin release-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-branch
          base: master
          title: "Release: New Maven Version"
          body: "This PR contains the release version changes."
